
spring:
  profiles:
    include: kinesis-local

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
aws:
  kinesis:
    region: local
    kinesis-url: http://localhost:4567
    consumer-group: example-service
    aws-account-id: "222222222222"
    iam-role-to-assume: ExampleKinesisRole
    create-streams: true
    dynamo-db-settings:
      url: http://localhost:8000